#!/bin/bash

echo Installing Homebrew…
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo Installing wget…
Brew install wget

echo Installing Chrome…
brew cask install google-chrome

echo Installing iTerm2…
brew cask install iterm2

