#!/bin/bash

echo Installing Homebrew…
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo Installing wget…
Brew install wget

echo Installing Google Chrome…
brew cask install google-chrome

echo Installing iTerm2…
brew cask install iterm2

echo Installing Zsh…
brew install zsh zsh-completions

echo Setting Zsh as default shell…
chsh -s /bin/zsh

echo Opening new window of terminal using zsh…
open -a iTerm ~/Applications/

echo Installing Oh My Zsh...
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo Installing Powerline Fonts...
# clone
git clone https://github.com/powerline/fonts.git
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts

echo Installing Sublime 3…
brew cask install sublime-text

echo Installing Flash…
brew cask install flash-npapi